### ISSUE TITLE
Not in GZIP format

### ISSUE THREAD

**Issue by SnUncle** [EndlessCodeGroup/RPGInventory#119]
My player cannot join the server because resourcepack can't be downland
when they join the sever The background will appear 
```
[15:12:27] [Server thread/WARN]: handleDisconnection() called twice 
```

and when i reload rpginventory this will appear 
```
[15:07:09] [Server thread/INFO]: [RPGInventory] Pet system is enabled.
[15:07:09] [Server thread/WARN]: java.lang.RuntimeException: java.util.zip.ZipException: Not in GZIP format
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.inventory.backpack.BackpackManager.tryToLoadBackpack(BackpackManager.java:190)
[15:07:09] [Server thread/WARN]: at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.Iterator.forEachRemaining(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.inventory.backpack.BackpackManager.loadBackpacks(BackpackManager.java:180)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.inventory.backpack.BackpackManager.init(BackpackManager.java:76)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:150)
[15:07:09] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:07:09] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[15:07:09] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.RPGInventoryCommandExecutor.reloadPlugin(RPGInventoryCommandExecutor.java:169)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.RPGInventoryCommandExecutor.onCommand(RPGInventoryCommandExecutor.java:252)
[15:07:09] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:07:09] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:07:09] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[15:07:09] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:627)
[15:07:09] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443)
[15:07:09] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:07:09] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[15:07:09] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[15:07:09] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)
[15:07:09] [Server thread/WARN]: Caused by: java.util.zip.ZipException: Not in GZIP format
[15:07:09] [Server thread/WARN]: at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[15:07:09] [Server thread/WARN]: at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.inventory.backpack.BackpackSerializer.loadBackpack(BackpackSerializer.java:72)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.inventory.backpack.BackpackManager.loadBackpack(BackpackManager.java:195)
[15:07:09] [Server thread/WARN]: at ru.endlesscode.rpginventory.inventory.backpack.BackpackManager.tryToLoadBackpack(BackpackManager.java:188)
[15:07:09] [Server thread/WARN]: ... 27 more\
```

**Comment by OsipXD** [comment]
Hello!
Try to delete content of `/backpacks` folder.

**Comment by OsipXD** [comment]
Closed because there no any activity.
