### ISSUE TITLE
Where I should configure resourcepacks?

### ISSUE THREAD

**Issue by asd86206** [EndlessCodeGroup/RPGInventory#123]
server.properties to set it?

**Comment by asd86206** [comment]
[16:58:23 WARN]: [RPGInventory] Task #21208 for RPGInventory v2.1.5 generated an exception
java.lang.NullPointerException
        at ru.endlesscode.rpginventory.inventory.PlayerWrapper.updatePermissions(PlayerWrapper.java:322) ~[?:?]
        at ru.endlesscode.rpginventory.event.updater.StatsUpdater.run(StatsUpdater.java:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by OsipXD** [comment]
No. In config.yml in section `resource-pack`
