### ISSUE TITLE
Task  BUG

### ISSUE THREAD

**Issue by asd86206** [EndlessCodeGroup/RPGInventory#124]
```
19.02 06:12:40 [Server] WARN Task #292449 for RPGInventory v2.1.5 generated an exception 
19.02 06:12:40 [Server] INFO java.lang.NullPointerException
 19.02 06:12:41 [Server] WARN Task #292490 for RPGInventory v2.1.5 generated an exception
 19.02 06:12:41 [Server] INFO java.lang.NullPointerException 
19.02 06:12:42 [Server] WARN Task #292497 for RPGInventory v2.1.5 generated an exception
 19.02 06:12:42 [Server] INFO java.lang.NullPointerException 
19.02 06:12:43 [Server] INFO aa910322 issued server command: /LIST
 19.02 06:12:44 [Server] WARN Task #292619 for RPGInventory v2.1.5 generated an exception
 19.02 06:12:44 [Server] INFO java.lang.NullPointerException
```

**Comment by Dereku** [comment]
Can you find the first message of the exception? There is no any information that can help us.

**Comment by asd86206** [comment]
This is the first message

**Comment by Dereku** [comment]
Nope, it's not.

**Comment by asd86206** [comment]
I will observe again

**Comment by asd86206** [comment]
[08:19:42] [Server thread/WARN]: [RPGInventory] Task #12145 for RPGInventory v2.1.5 generated an exception
java.lang.NullPointerException
	at ru.endlesscode.rpginventory.inventory.PlayerWrapper.updatePermissions(PlayerWrapper.java:322) ~[?:?]
	at ru.endlesscode.rpginventory.event.updater.StatsUpdater.run(StatsUpdater.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by asd86206** [comment]
[08:19:42] [Server thread/WARN]: [RPGInventory] Task #12145 for RPGInventory v2.1.5 generated an exception
java.lang.NullPointerException
	at ru.endlesscode.rpginventory.inventory.PlayerWrapper.updatePermissions(PlayerWrapper.java:322) ~[?:?]
	at ru.endlesscode.rpginventory.event.updater.StatsUpdater.run(StatsUpdater.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[08:19:43] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:616) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at ru.endlesscode.rpginventory.item.ItemManager.allowedForPlayer(ItemManager.java:157) ~[?:?]
	at ru.endlesscode.rpginventory.utils.InventoryUtils.collectEffectiveItems(InventoryUtils.java:94) ~[?:?]
	at ru.endlesscode.rpginventory.item.ItemManager.getModifier(ItemManager.java:105) ~[?:?]
	at ru.endlesscode.rpginventory.item.ItemManager.getModifier(ItemManager.java:101) ~[?:?]
	at ru.endlesscode.rpginventory.event.listener.ItemListener.onPlayerJump(ItemListener.java:155) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	... 15 more

**Comment by Dereku** [comment]
Fixed, please wait for the plugin update.

**Comment by asd86206** [comment]
He will cause the player to enter the server

Will LAG
