### ISSUE TITLE
Exception on Player death

### ISSUE THREAD

**Issue by emt8888** [EndlessCodeGroup/RPGInventory#144]
```
Could not pass event PlayerDeathEvent to RPGInventory v2.1.6-PRE
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[mc.jar:git-Spigot-3fb9445-6e3cec8]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-3fb9445-6e3cec8]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityPlayer.die(EntityPlayer.java:420) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:782) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:505) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityMonster.B(EntityMonster.java:68) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityZombie.B(EntityZombie.java:202) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:129) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:658) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityZombie.n(EntityZombie.java:155) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [mc.jar:git-Spigot-3fb9445-6e3cec8]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
```

**Comment by OsipXD** [comment]
It's not full exception. What after `Caused by: java.lang.NullPointerException`?

**Comment by emt8888** [comment]
When the player dies

**Comment by emt8888** [comment]
No, this occurrs only when player is killed

**Comment by emt8888** [comment]
[19:52:11] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to RPGInventory v2.1.6-PRE
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.die(EntityPlayer.java:420) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:782) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:505) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.B(EntityMonster.java:68) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityZombie.B(EntityZombie.java:202) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:129) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:658) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityZombie.n(EntityZombie.java:155) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
[19:52:11] [Server thread/INFO]: Xi_Gua_ was slain by §c嗜血蝙蝠[Lv19]
[19:52:12] [Server thread/INFO]: bguuqo issued server command: /j
[19:52:12] [Server thread/INFO]: 已发送[m
[19:52:12] [Server thread/INFO]: bguuqo issued server command: /title bguuqo title ["",{"text":"飞空艇已经到达绿幽城上方了!","color":"dark_aqua"}]
[19:52:12] [Server thread/INFO]: [bguuqo: Title command successfully executed]
[19:52:12] [Server thread/INFO]: 已发送[m

**Comment by Dereku** [comment]
When player has been killed by a mob. Ok, got it.

**Comment by emt8888** [comment]
[07:46:08] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to RPGInventory v2.1.6-PRE
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.die(EntityPlayer.java:420) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:782) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:505) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.B(EntityMonster.java:68) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityZombie.B(EntityZombie.java:202) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:129) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:658) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityZombie.n(EntityZombie.java:155) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [mc.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at ru.endlesscode.rpginventory.utils.ItemUtils.toBukkitItemStack(ItemUtils.java:254) ~[?:?]
	at ru.endlesscode.rpginventory.utils.ItemUtils.getTag(ItemUtils.java:90) ~[?:?]
	at ru.endlesscode.rpginventory.utils.ItemUtils.getTag(ItemUtils.java:84) ~[?:?]
	at ru.endlesscode.rpginventory.item.ItemManager.getCustomItem(ItemManager.java:144) ~[?:?]
	at ru.endlesscode.rpginventory.inventory.InventorySaver.save(InventorySaver.java:60) ~[?:?]
	at ru.endlesscode.rpginventory.event.listener.PlayerListener.onPlayerDead(PlayerListener.java:128) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[mc.jar:git-Spigot-3fb9445-6e3cec8]
	... 31 more

**Comment by OsipXD** [comment]
Thanks it is very helpful
