### ISSUE TITLE
Bug ServerCore:KCauldorn 1710

### ISSUE THREAD

**Issue by nmxs2468** [EndlessCodeGroup/RPGInventory#19]
[18:29:09 ERROR]: Cannot load plugins\RPGInventory\lang\en.lang
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xFFFD) special characters are not allowed
in "", position 681
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[YamlConfiguration.class:1.7.10-R0.1-SNAPSHOT]…[18:29:10 WARN]: java.lang.NoSuchFieldException: item
[18:29:10 WARN]: at java.lang.Class.getDeclaredField(Unknown Source)
[18:29:10 WARN]: at ru.endlesscode.rpginventory.utils.ItemUtils.setMaxStackSize(ItemUtils.java:23)
[18:29:10 WARN]: at ru.endlesscode.rpginventory.inventory.InventoryLocker.(InventoryLocker.java:49)
[18:29:10 WARN]: at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:116)
[18:29:10 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:29:10 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:29:10 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:29:10 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:29:10 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:29:10 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:29:10 WARN]: at java.lang.Thread.run(Unknown Source)
[18:29:10 WARN]: java.lang.NoSuchFieldException: item
[18:29:10 WARN]: at java.lang.Class.getDeclaredField(Unknown Source)
[18:29:10 WARN]: at ru.endlesscode.rpginventory.utils.ItemUtils.setMaxStackSize(ItemUtils.java:23)
[18:29:10 WARN]: at ru.endlesscode.rpginventory.inventory.InventoryLocker.(InventoryLocker.java:59)
[18:29:10 WARN]: at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:116)
[18:29:10 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:29:10 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:29:10 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:29:10 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:29:10 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:29:10 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:29:10 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:29:10 WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by OsipXD** [comment]
You've used standart locale files? Looks like en.yml encoding is wrong. What encoding you use on server by default?

**Comment by nmxs2468** [comment]
Yes,I use locale files.I use en.yml

**Comment by OsipXD** [comment]
What encoding?

**Comment by nmxs2468** [comment]
Error two
[00:00:33 ERROR]: Error occurred while enabling RPGInventory v1.3.5 (Is it up to date?)
java.lang.NumberFormatException: For input string: "Ghast"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Byte.parseByte(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Byte.parseByte(Unknown Source) ~[?:1.8.0_121]
        at ru.endlesscode.rpginventory.utils.ItemUtils.getTexturedItem(ItemUtils.java:105) ~[?:?]
        at ru.endlesscode.rpginventory.pet.PetType.createSpawnItem(PetType.java:206) ~[?:?]
        at ru.endlesscode.rpginventory.pet.PetType.<init>(PetType.java:73) ~[?:?]
        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:81) ~[?:?]
        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:144) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by OsipXD** [comment]
Yes, I'm about lang file.
About second error - read [here](http://minecraft.gamepedia.com/Spawn_Egg#History) about changes in mc 1.9, And use aggs id's instead of mob names

**Comment by nmxs2468** [comment]
Change pet.yml?

**Comment by OsipXD** [comment]
Yes

**Comment by nmxs2468** [comment]
Like this item: MONSTER_EGG:56?

**Comment by OsipXD** [comment]
Yes

**Comment by nmxs2468** [comment]
Error still the same

**Comment by nmxs2468** [comment]
[20:59:20 ERROR]: Could not pass event InventoryCloseEvent to RPGInventory v1.2.8
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:906) [CraftEventFactory.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.func_147356_a(NetHandlerPlayServer.java:1639) [nh.class:?]
        at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(C0DPacketCloseWindow.java:27) [iy.class:?]
        at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(C0DPacketCloseWindow.java:42) [iy.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
        at ru.endlesscode.rpginventory.inventory.chest.ChestWrapper.setContents(ChestWrapper.java:70) ~[?:?]
        at ru.endlesscode.rpginventory.event.listener.ChestListener.onInventoryClose(ChestListener.java:79) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        ... 14 more

**Comment by nmxs2468** [comment]
Use Kcauldron,thermos heve so many bugs QWQ

**Comment by OsipXD** [comment]
Try to use alternate view

**Comment by nmxs2468** [comment]
give you picture?

**Comment by OsipXD** [comment]
What you mean?

**Comment by nmxs2468** [comment]
(Try to use alternate view) is give you picture?

**Comment by nmxs2468** [comment]
I change pet.yml like this
pets:
  kitty:
    name: "&7&lKitty"
    item-name: "&7&lKitty's Summoning Stone"
    lore: "&e&oMeow! Meow! Meow!"
    item: MONSTER_EGG:58
    type: COMPANION
    skin: OCELOT
    health: 20
    damage: 3
    speed: 1
    attack-mobs: true
    attack-players: false
    revival: true
    cooldown: 60
    features:
    - "BABY: TRUE"
but will have [warn]
[08:08:12 WARN]: java.lang.NullPointerException
[08:08:12 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:104)
[08:08:12 WARN]:        at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:29)
[08:08:12 WARN]:        at ru.endlesscode.rpginventory.pet.PetType.createDisguise(PetType.java:95)
[08:08:12 WARN]:        at ru.endlesscode.rpginventory.pet.PetType.<init>(PetType.java:70)
[08:08:12 WARN]:        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:79)
[08:08:12 WARN]:        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:141)
[08:08:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[08:08:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[08:08:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[08:08:12 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[08:08:12 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[08:08:12 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[08:08:12 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[08:08:12 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[08:08:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[08:08:12 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[08:08:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[08:08:12 INFO]: [RPGInventory] 1 pet(s) has been loaded
[08:08:12 ERROR]: Error occurred while enabling RPGInventory v1.2.7 (Is it up to date?)
java.lang.NullPointerException
        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:85) ~[?:?]
        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by nmxs2468** [comment]
Sorry my English is very bad...

**Comment by OsipXD** [comment]
What options you changed?

**Comment by nmxs2468** [comment]
Deleted the other pets

**Comment by OsipXD** [comment]
Are there any more errors in the console?

**Comment by nmxs2468** [comment]
1.
[20:49:25 ERROR]: Error occurred while enabling RPGInventory v1.2.7 (Is it up to date?)
java.lang.NullPointerException
        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:85) ~[?:?]
        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[20:49:24 INFO]: [RPGInventory] Permissions hooked: GroupManager
[20:49:24 INFO]: [RPGInventory] Economy hooked: Essentials Economy
[20:49:24 INFO]: [RPGInventory] PacketWrapper hooked.
[20:49:24 INFO]: [RPGInventory] 3 backpack type(s) has been loaded
[20:49:24 INFO]: [RPGInventory] 1 backpack(s) has been loaded
[20:49:24 INFO]: [RPGInventory] 1 item(s) has been loaded
[20:49:25 WARN]: java.lang.NullPointerException
[20:49:25 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:104)
[20:49:25 WARN]:        at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:29)
[20:49:25 WARN]:        at ru.endlesscode.rpginventory.pet.PetType.createDisguise(PetType.java:95)
[20:49:25 WARN]:        at ru.endlesscode.rpginventory.pet.PetType.<init>(PetType.java:70)
[20:49:25 WARN]:        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:79)
[20:49:25 WARN]:        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:141)
[20:49:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[20:49:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[20:49:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[20:49:25 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[20:49:25 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[20:49:25 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[20:49:25 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[20:49:25 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[20:49:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[20:49:25 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[20:49:25 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by nmxs2468** [comment]
1error and some warn

**Comment by OsipXD** [comment]
Give me your pets.yml as file

**Comment by nmxs2468** [comment]
pets:
  kitty:
    name: "&7&lKitty"
    item-name: "&7&lKitty's Summoning Stone"
    lore: "&e&oMeow! Meow! Meow!"
    item: MONSTER_EGG:58
    type: COMPANION
    skin: OCELOT
    health: 20
    damage: 3
    speed: 1
    attack-mobs: true
    attack-players: false
    revival: true
    cooldown: 60
    features:
    - "BABY: TRUE"

**Comment by OsipXD** [comment]
No. As file not as text

**Comment by nmxs2468** [comment]
ok
https://drive.google.com/open?id=0B-6UVp9N5p89Q0haYVB6QURnNGM

**Comment by nmxs2468** [comment]
Player join server 
[11:03:08 WARN]: [RPGInventory] Task #109 for RPGInventory v1.2.7 generated an exception
java.lang.NullPointerException
        at ru.endlesscode.rpginventory.inventory.InventoryLocker.getBuyableSlotForLine(InventoryLocker.java:81) ~[?:?]
        at ru.endlesscode.rpginventory.inventory.InventoryLocker.lockSlots(InventoryLocker.java:128) ~[?:?]
        at ru.endlesscode.rpginventory.inventory.InventoryLocker.lockSlots(InventoryLocker.java:113) ~[?:?]
        at ru.endlesscode.rpginventory.inventory.InventoryManager.loadPlayerInventory(InventoryManager.java:397) ~[?:?]
        at ru.endlesscode.rpginventory.event.listener.InventoryListener$4.run(InventoryListener.java:424) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[11:03:08 ERROR]: [RPGInventory] Error while decryption:
javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:934) ~[sunjce_provider.jar:1.8.0_112]
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:845) ~[sunjce_provider.jar:1.8.0_112]
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446) ~[sunjce_provider.jar:1.8.0_112]
        at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[?:1.8.0_121]
        at ru.endlesscode.rpginventory.misc.updater.Updater.read(Updater.java:578) [RPGInventory%20(1).jar:?]
        at ru.endlesscode.rpginventory.misc.updater.Updater.runUpdater(Updater.java:646) [RPGInventory%20(1).jar:?]
        at ru.endlesscode.rpginventory.misc.updater.Updater.access$200(Updater.java:45) [RPGInventory%20(1).jar:?]
        at ru.endlesscode.rpginventory.misc.updater.Updater$UpdateRunnable.run(Updater.java:764) [RPGInventory%20(1).jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by evernife** [comment]
Just to keep this updated, the last error on Thermos is [this one](https://hastebin.com/moyuyeqogi.css)! Occurs on plugin load;

**Comment by OsipXD** [comment]
Closed, because outdated
