### ISSUE TITLE
New Bug! DeathEvent

### ISSUE THREAD

**Issue by DonatEW** [EndlessCodeGroup/RPGInventory#28]
[18:26:42] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to RPGInventory v2.0.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.die(EntityPlayer.java:420) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:782) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:505) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.EntityArrow.a(EntityArrow.java:286) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.EntityArrow.A_(EntityArrow.java:194) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.EntityTippedArrow.A_(EntityTippedArrow.java:86) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at ru.endlesscode.rpginventory.inventory.InventorySaver.save(InventorySaver.java:64) ~[?:?]
	at ru.endlesscode.rpginventory.event.listener.PlayerListener.onPlayerDead(PlayerListener.java:127) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1083.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3fb9445-fbb47e8]
	... 20 more

**Comment by OsipXD** [comment]
Thanks for report. Does this occur at every death?

**Comment by DonatEW** [comment]
There is not every death.

**Comment by DonatEW** [comment]
На русском можно отвечать?

**Comment by OsipXD** [comment]
Да можете
