### ISSUE TITLE
Custom Pets:

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#47]
Ability to make Custom Pets would be fantastic! I tried adding one in the Config, thinking I could, and it would just delete any data I put in the file, and not allow me to make one at all. Possibility I am doing it wrong, so I apologize in advance.

(or): Add MyPet support, so you can turn your MyPet pet into an Summoning Egg as well.

**Comment by OsipXD** [comment]
Have you tried to create slot with type `MYPET`?
And have you any arrors in logs?

**Comment by KnifeKat** [comment]
I will try that out tonight.

**Comment by KnifeKat** [comment]
Got this when making the slot type: "MYPET"

[RPGInventory] Item system is enabled.
[03:55:51 WARN]: java.lang.IllegalArgumentException: No enum constant ru.endlesscode.rpginventory.pet.PetType.Role.MYPET
[03:55:51 WARN]:        at java.lang.Enum.valueOf(Unknown Source)
[03:55:51 WARN]:        at ru.endlesscode.rpginventory.pet.PetType$Role.valueOf(PetType.java:220)
[03:55:51 WARN]:        at ru.endlesscode.rpginventory.pet.PetType.<init>(PetType.java:74)
[03:55:51 WARN]:        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:86)
[03:55:51 WARN]:        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:129)
[03:55:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:55:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[03:55:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[03:55:51 WARN]:        at ru.endlesscode.rpginventory.RPGInventoryCommandExecutor.reloadPlugin(RPGInventoryCommandExecutor.java:174)
[03:55:51 WARN]:        at ru.endlesscode.rpginventory.RPGInventoryCommandExecutor.onCommand(RPGInventoryCommandExecutor.java:279)
[03:55:51 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[03:55:51 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[03:55:51 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[03:55:51 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:633)
[03:55:51 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[03:55:51 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[03:55:51 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[03:55:51 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[03:55:51 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by OsipXD** [comment]
Do you have slot with type PET?
And what errors you getting?
