### ISSUE TITLE
Won't load 

### ISSUE THREAD

**Issue by tara81** [EndlessCodeGroup/RPGInventory#48]
v 2.0.9
spigot 1.9.4

[17:09:28] [Server thread/INFO]: [RPGInventory] Enabling RPGInventory v2.0.9
[17:09:28] [Server thread/INFO]: [RPGInventory] Permissions hooked: bPermissions2
[17:09:28] [Server thread/INFO]: [RPGInventory] Economy hooked: Craftconomy3
[17:09:28] [Server thread/WARN]: java.lang.RuntimeException: Cannot find CraftItemStack.asCraftMirror(net.minecraft.server.ItemStack).
[17:09:28] [Server thread/WARN]: 	at com.comphenix.protocol.utility.MinecraftReflection.getBukkitItemByMethod(MinecraftReflection.java:1911)
[17:09:28] [Server thread/WARN]: 	at com.comphenix.protocol.utility.MinecraftReflection.getBukkitItemStack(MinecraftReflection.java:1891)
[17:09:28] [Server thread/WARN]: 	at ru.endlesscode.rpginventory.utils.ItemUtils.toBukkitItemStack(ItemUtils.java:245)
[17:09:28] [Server thread/WARN]: 	at ru.endlesscode.rpginventory.utils.ItemUtils.setTag(ItemUtils.java:64)
[17:09:28] [Server thread/WARN]: 	at ru.endlesscode.rpginventory.utils.ItemUtils.getTexturedItem(ItemUtils.java:125)
[17:09:28] [Server thread/WARN]: 	at ru.endlesscode.rpginventory.inventory.InventoryManager.init(InventoryManager.java:71)
[17:09:28] [Server thread/WARN]: 	at ru.endlesscode.rpginventory.RPGInventory.checkRequirements(RPGInventory.java:214)
[17:09:28] [Server thread/WARN]: 	at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:111)
[17:09:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[17:09:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[17:09:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:09:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361)
[17:09:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321)
[17:09:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416)
[17:09:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381)
[17:09:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336)
[17:09:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268)
[17:09:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[17:09:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:09:28] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_9_R2.inventory.CraftItemStack.asCraftMirror(org.bukkit.inventory.ItemStack)
[17:09:28] [Server thread/WARN]: 	at java.lang.Class.getMethod(Class.java:1786)
[17:09:28] [Server thread/WARN]: 	at com.comphenix.protocol.utility.MinecraftReflection.getBukkitItemByMethod(MinecraftReflection.java:1908)
[17:09:28] [Server thread/WARN]: 	... 18 more
[17:09:28] [Server thread/INFO]: [RPGInventory] Disabling RPGInventory v2.0.9

**Comment by tara81** [comment]
nvm - was able to load with protocollib update.
