### ISSUE TITLE
Error RPInventory v2.1.2, move weapon and all interval

### ISSUE THREAD

**Issue by hironasi0165** [EndlessCodeGroup/RPGInventory#64]
Hi Author!
Error RPInventory v2.1.2
- I can move weapon and all interval, link image: https://imgur.com/a/KoQ76
- Server me minecraft ver 1.9.4
- Spam console:
`[Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getWidth()D
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.isPlayerCanFall(ElytraListener.java:61) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:46) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    ... 15 more
[00:34:04] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getWidth()D
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.isPlayerCanFall(ElytraListener.java:61) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:46) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    ... 15 more
[00:34:04] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getWidth()D
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.isPlayerCanFall(ElytraListener.java:61) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:46) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    ... 15 more
[00:34:04] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getWidth()D
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.isPlayerCanFall(ElytraListener.java:61) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:46) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    ... 15 more
[00:34:04] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-c6871e2-0cd0397]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getWidth()D
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.isPlayerCanFall(ElytraListener.java:61) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:46) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
    ... 15 more`

**Comment by Dereku** [comment]
@OsipXD , Player#getWidth()? 
https://github.com/EndlessCodeGroup/RPGInventory/blob/master/src/main/java/ru/endlesscode/rpginventory/event/listener/ElytraListener.java#L61

**Comment by KnifeKat** [comment]
Looks like the guy just literally has no idea how to make the config correctly. >_>;

**Comment by hironasi0165** [comment]
My problem is still not resolved?

**Comment by OsipXD** [comment]
It will be resolved in new version. Now you can use v2.1.1
