### ISSUE TITLE
error in game

### ISSUE THREAD

**Issue by Fargus5** [EndlessCodeGroup/RPGInventory#72]
[16:30:49] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:647) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at ru.endlesscode.rpginventory.pet.PetManager.isPetItem(PetManager.java:395) ~[?:?]
    at ru.endlesscode.rpginventory.inventory.PlayerWrapper.stopFlight(PlayerWrapper.java:276) ~[?:?]
    at ru.endlesscode.rpginventory.inventory.PlayerWrapper.setFalling(PlayerWrapper.java:256) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:56) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    ... 15 more
[16:31:02] [Server thread/INFO]: Hirluim issued server command: //copy
[16:31:02] [Craft Scheduler Thread - 96/INFO]: (FAWE) Running 1.12 registry dumper!
[16:31:02] [Craft Scheduler Thread - 96/INFO]: (FAWE) Using adapter: com.boydti.fawe.bukkit.v1_12.FaweAdapter_1_12@a0186c9
[16:31:02] [Craft Scheduler Thread - 96/INFO]: (FAWE) =========================================
[16:31:04] [Server thread/INFO]: Hirluim issued server command: //flip
[16:31:06] [Server thread/INFO]: Hirluim issued server command: //paste
[16:31:06] [ForkJoinPool-2-worker-1/WARN]: Ignoring unknown attribute 'generic.attackDamage'
[16:31:18] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:647) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at ru.endlesscode.rpginventory.pet.PetManager.isPetItem(PetManager.java:395) ~[?:?]
    at ru.endlesscode.rpginventory.inventory.PlayerWrapper.stopFlight(PlayerWrapper.java:276) ~[?:?]
    at ru.endlesscode.rpginventory.inventory.PlayerWrapper.setFalling(PlayerWrapper.java:256) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:56) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    ... 15 more
[16:31:22] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:647) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at ru.endlesscode.rpginventory.pet.PetManager.isPetItem(PetManager.java:395) ~[?:?]
    at ru.endlesscode.rpginventory.inventory.PlayerWrapper.stopFlight(PlayerWrapper.java:276) ~[?:?]
    at ru.endlesscode.rpginventory.inventory.PlayerWrapper.setFalling(PlayerWrapper.java:256) ~[?:?]
    at ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFall(ElytraListener.java:56) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    ... 15 more

**Comment by Fargus5** [comment]
14:39:42 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:39:43 CONSOLE: Source) ~[?:?]
14:39:44 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:39:44 CONSOLE: Source) ~[?:?]
14:39:45 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:39:45 CONSOLE: Source) ~[?:?]
14:39:47 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:39:47 CONSOLE: Source) ~[?:?]
14:39:52 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:39:52 CONSOLE: Source) ~[?:?]
14:39:53 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:39:53 CONSOLE: Source) ~[?:?]
14:39:56 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:39:56 CONSOLE: Source) ~[?:?]
14:40:00 CONSOLE: [INFO] Hirluim issued server command: /back
14:40:03 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:40:04 CONSOLE: Source) ~[?:?]
14:40:04 CONSOLE: ERROR]: Could not pass event PlayerMoveEvent to RPGInventory v2.1.2
14:40:05 CONSOLE: Source) ~[?:?]
